### PR TITLE
Fix builds on Fedora platforms.

### PR DESCRIPTION
**Pull request by simonmichal**

### CODE REVIEW

**Comment by djw8605** [comment]
I'm not a fan of putting an XRootD dependency on vendor code.  And strncpy is a standard function, right?

**Comment by simonmichal** [comment]
Well, `strncpy` is a standard function, however it does not make sure the string will be null terminated, hence if one copies as many characters as the destination buffer size one will get a warning and as we are treating all warnings as errors this breaks our builds:

```
/xrootd/src/XrdSciTokens/XrdSciTokens/vendor/inih/INIReader.h:163:12: error: 'char* strncpy(char*, const char*, size_t)' specified bound 50 equals destination size [-Werror=stringop-truncation]
     strncpy(dest, src, size);
```

also, have a look at:
https://gitlab.cern.ch/dss/xrootd/-/pipelines/2024647
it breaks cc7, centos8 and all fedora builds ;-)

that said, I don't have any strong feelings about using `strlcpy` (though I don't think it's a bad idea, we are using it widely in XRootD), I would like just the builds to be green! ;-)

**Comment by abh3** [comment]
Frankly, as a compromoise use memcpy one short of length and add a null 
byte. Crappy but the compiler will then not complain and we won't have a 
dependency.

Andy

**Comment by djw8605** [comment]
There is a pull request in the inih project for replacing this function with `strncpy_s`.  I'm not familiar with the behavior of this function.  Does that function solve the fedora builds?
https://github.com/jtilly/inih/pull/21/files

**Comment by abh3** [comment]
Sounds like a reasonable solution and we should replace strlcpy() with 
strncpy_s()!

**Comment by simonmichal** [comment]
@djw8605 : I updated the PR so it is in line with https://github.com/jtilly/inih/pull/21/files, for now I will update xrootd core so it builds against the `fixfedora` branch in order to have CI builds green.

**Comment by simonmichal** [comment]
hmmm it turns out that `GCC` does not support `strncpy_s` :|

**Comment by simonmichal** [comment]
So I changed the PR so it uses `memcpy` instead of `strncpy` for now.

How should we proceed?

**Comment by djw8605** [comment]
Redhat has an article where they recommend strcpy or memcpy: https://developers.redhat.com/blog/2018/05/24/detecting-string-truncation-with-gcc-8/

> In general, it is not possible to avoid string truncation by strncpy except by sizing the destination to be at least a byte larger than the length of the source string. With that approach, however, using strncpy becomes unnecessary and the function can be avoided in favor of other APIs such as strcpy or (less preferably) memcpy. Much has been written about the problems with strncpy and we recommend to avoid it whenever possible. It is, however, worth keeping in mind that unlike other standard string-handling functions, strncpy always writes exactly as many characters as specified by the third argument; if the source string is shorter, the function fills the remaining bytes with NULs.

**Comment by abh3** [comment]
Well, almost. It depends on the type of checking you use. If you run 
source through a static analysis regime like Coverity (which we used to 
do) you will be flooded with complaints about strcpy() even if you 
size things correctly. If you specify strict length checking (which we do) 
then the compiler will complain the moment it senses that the target might 
not be sized correctly and it comes with a lot of false positives. I still 
like the idea of simply using std::strncpy_s which avoids both of these 
problems. The Redhat solution obviously works but it's a practical 
solution to avoid error messages but unfortunately it hides incorrect 
usage.

Andy

On Thu, 29 Oct 2020, Derek Weitzel wrote:

> Redhat has an article where they recommend strcpy or memcpy: 
> https://developers.redhat.com/blog/2018/05/24/detecting-string-truncation-with-gcc-8/
>
>> In general, it is not possible to avoid string truncation by strncpy 
except by sizing the destination to be at least a byte larger than the 
length of the source string. With that approach, however, using strncpy 
becomes unnecessary and the function can be avoided in favor of other 
APIs such as strcpy or (less preferably) memcpy. Much has been written 
about the problems with strncpy and we recommend to avoid it whenever 
possible. It is, however, worth keeping in mind that unlike other 
standard string-handling functions, strncpy always writes exactly as many 
characters as specified by the third argument; if the source string is 
shorter, the function fills the remaining bytes with NULs.

**Comment by djw8605** [comment]
I too wish that strncpy_s was included in glibc.  If fedora is ok with it, I'm ok with memcpy.

**Comment by abh3** [comment]
Yep, while most docs show this part of the C++ standard it is, in fact, 
an "optional" function. GNU among others decided not to implement it. 
However, there is an exact equivalent for this that I have used at times:

snprintf(buff, sizeof(buff), "%s", source)

it works like a charm and even tells you if truncation occurred.

**Comment by simonmichal** [comment]
Well, the goal of the function in question is to provide `Version of strncpy that ensures dest (size bytes) is null-terminated.` :

https://github.com/xrootd/xrootd-scitokens/blob/d200b85df9293ea49ee7d7c845173d17a25c645b/vendor/inih/INIReader.h#L160-L166

I don't think `strcpy` will go the job as this one does not allow to specify the size.

Indeed probably `snprintf(buff, sizeof(buff), "%s", source)` is the closed to what we want, so if there is an agreement that that's the way to go, I'll change the PR. Please let me know!

**Comment by djw8605** [comment]
Agreed, snprintf sounds like the best option.

**Comment by simonmichal** [comment]
OK, I have changed the PR, `snprintf` it is!

**Comment by abh3** [comment]
I am fine with strncpy. I think the performance is about the same as the 
provided strlcpy in XrdSysPlatform.hh.

Andy

**Comment by simonmichal** [comment]
@djw8605 : so what's the verdict, is it good enough to be merged? ;-)

**Comment by djw8605** [comment]
I'm happy, merging.

**Pull request merged**
